
name: NKTLIB mc68020-40 nolibc
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'build/**'
      - 'DOCS/**'
      - 'sample_music/**'
      - 'scripts/**'
      - 'images/**'
      - 'extools/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-nktlib-020-40-nolibc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Installing build prerequisities
        run: |
          echo Update and get build prerequisities
          sudo apt-get update -qq
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y scons upx
      
      - name: Installing VASM
        run: |
          echo Get and install vasm
          wget -q "https://nokturnal.pl/downloads/atari/toolchains/vasm.tar.gz"
          tar -xvf ./vasm.tar.gz
          cd ./vasm
          make -j12 CPU=m68k SYNTAX=mot
          sudo cp ./vasmm68k_mot /usr/bin/
          sudo cp ./vobjdump /usr/bin/
          cd ..
      
      - name: Installing gcc minimal startup
        run: |
          echo Getting latest gcc minimal startup
          sudo chmod +x ./scripts/getLatestStartup.sh
          ./scripts/getLatestStartup.sh

      - name: Installing gcc cross compiler
        run: |
          echo Installing gcc in /opt/m68k-ataritos/aout
          sudo mkdir /opt/m68k-ataritos/
          sudo mkdir /opt/m68k-ataritos/aout
          sudo chgrp users /opt/m68k-ataritos/aout
          sudo chmod 775 /opt/m68k-ataritos/aout
          wget -q "https://nokturnal.pl/downloads/atari/toolchains/m68k-atari-mint-base-20200501-linux64.tar.xz"
          tar -C /opt/m68k-ataritos/aout --strip-components=1 -xf ./m68k-atari-mint-base-20200501-linux64.tar.xz
      
      - name: Build nktlib (nolibc) version
        run: |
          cd ./nktlib
          chmod +x ./updateNktLibBuildFiles.sh
          chmod +x ./rebuild_020-40_nolibc_release.sh
          ./updateNktLibBuildFiles.sh
          ./rebuild_020-40_nolibc_release.sh

      - name: Upload nktlib (nolibc) archive
        uses: actions/upload-artifact@v3
        with:
          name: nktlib-020-40-nolibc
          path: ./nktlib/nktlib-*.tgz
          retention-days: 7
          